#!/usr/bin/env python3
"""Generate crawlable work pages and a sitemap from assets/data/works.json."""

from __future__ import annotations

import argparse
from html import escape, unescape
import json
from pathlib import Path
import re
import sys
from urllib.parse import unquote, urljoin, urlparse
from xml.sax.saxutils import escape as xml_escape


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assets" / "data" / "works.json"
DETAIL_TEMPLATE_PATH = ROOT / "templates" / "work-detail.html"
WORKS_INDEX_PATH = ROOT / "works" / "index.html"
SITEMAP_PATH = ROOT / "sitemap.xml"
ROBOTS_PATH = ROOT / "robots.txt"
BASE_URL = "https://yeoneui.kim"
INDEX_START = "<!-- STATIC_WORK_CARDS_START -->"
INDEX_END = "<!-- STATIC_WORK_CARDS_END -->"
SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TAG_PATTERN = re.compile(r"<[^>]+>")
BREAK_PATTERN = re.compile(r"<br\s*/?>", re.IGNORECASE)
GENERATED_MARKER = "<!-- Generated from assets/data/works.json; do not edit this file directly. -->"


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when generated files are missing or stale instead of writing them.",
    )
    return parser.parse_args()


def plain_text(value: object) -> str:
    text = BREAK_PATTERN.sub(" / ", str(value or ""))
    text = TAG_PATTERN.sub("", text)
    return " ".join(unescape(text).split())


def meta_description(work: dict) -> str:
    source = plain_text(work.get("abstract")) or plain_text(work.get("detail"))
    suffix = " — Yeoneui Kim 김연의"
    limit = 160 - len(suffix)
    if len(source) > limit:
        shortened = source[: limit + 1].rsplit(" ", 1)[0].rstrip(" ,./")
        source = f"{shortened}…"
    return f"{source}{suffix}"


def site_path(value: str) -> str:
    value = value.strip()
    if re.match(r"^(?:https?:)?//", value):
        return value
    while value.startswith("../"):
        value = value[3:]
    if value.startswith("./"):
        value = value[2:]
    return f"/{value.lstrip('/')}"


def absolute_url(value: str) -> str:
    path = site_path(value)
    if re.match(r"^(?:https?:)?//", path):
        return path
    return urljoin(f"{BASE_URL}/", path.lstrip("/"))


def derive_hover_thumbnail(thumbnail: str) -> str:
    match = re.match(r"^(.*?)(\.[^./?#]+)([?#].*)?$", thumbnail)
    if not match:
        return f"{thumbnail}2"
    return f"{match.group(1)}2{match.group(2)}{match.group(3) or ''}"


def load_works() -> list[dict]:
    with DATA_PATH.open(encoding="utf-8") as handle:
        works = json.load(handle)
    if not isinstance(works, list) or not works:
        raise ValueError("works.json must contain a non-empty array.")

    required = ("id", "slug", "title", "thumbnail", "mainImage", "year", "분류")
    ids: set[str] = set()
    slugs: set[str] = set()
    for index, work in enumerate(works):
        if not isinstance(work, dict):
            raise ValueError(f"Work at index {index} is not an object.")
        missing = [field for field in required if not str(work.get(field, "")).strip()]
        if missing:
            raise ValueError(f"{work.get('id', index)} is missing: {', '.join(missing)}")
        work_id = str(work["id"])
        slug = str(work["slug"])
        if work_id in ids:
            raise ValueError(f"Duplicate work id: {work_id}")
        if slug in slugs:
            raise ValueError(f"Duplicate slug: {slug}")
        if not SLUG_PATTERN.fullmatch(slug):
            raise ValueError(f"Invalid slug for {work_id}: {slug}")
        ids.add(work_id)
        slugs.add(slug)
    return works


def detail_images(work: dict) -> list[dict[str, str]]:
    title = plain_text(work["title"])
    explicit = work.get("detailImages")
    if isinstance(explicit, list):
        images: list[dict[str, str]] = []
        for index, item in enumerate(explicit, start=1):
            if not isinstance(item, str):
                raise ValueError(f"detailImages must contain paths for {work['id']} at position {index}")
            src = item.strip()
            alt = f"{title} — 상세 이미지 {index} / Detail image {index}"
            if not src:
                raise ValueError(f"Empty detail image path for {work['id']} at position {index}")
            images.append({"src": site_path(src), "alt": alt})
        return images

    images = []
    folder = ROOT / "assets" / "images" / str(work["id"])
    index = 1
    while True:
        filename = f"detail{index}.jpg"
        if not (folder / filename).is_file():
            break
        images.append(
            {
                "src": f"/assets/images/{work['id']}/{filename}",
                "alt": f"{title} — 상세 이미지 {index} / Detail image {index}",
            }
        )
        index += 1
    return images


def work_card(work: dict) -> str:
    title = plain_text(work["title"])
    thumbnail = site_path(str(work["thumbnail"]))
    hover = site_path(str(work.get("hoverThumbnail") or derive_hover_thumbnail(str(work["thumbnail"]))))
    return f'''<div class="work-item">
    <a href="/works/{escape(str(work['slug']), quote=True)}/">
        <div class="image-wrapper">
            <img src="{escape(thumbnail, quote=True)}" alt="{escape(title, quote=True)} 썸네일 / Thumbnail" class="work-thumbnail" loading="lazy">
            <img src="{escape(hover, quote=True)}" alt="" class="work-thumbnail hover-img" loading="lazy" aria-hidden="true">
        </div>
        <h3 class="worktitle">{work['title']}</h3>
        <p class="subtitle">{work.get('subtitle', '')}</p>
        <p class="filter">{escape(str(work['분류']))}</p>
    </a>
</div>'''


def render_index(current: str, works: list[dict]) -> str:
    cards = "\n".join(work_card(work) for work in reversed(works))
    replacement = f"{INDEX_START}\n{cards}\n{INDEX_END}"
    pattern = re.compile(re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END), re.DOTALL)
    if not pattern.search(current):
        raise ValueError("works/index.html is missing static card markers.")
    return pattern.sub(replacement, current)


def render_detail_content(work: dict, images: list[dict[str, str]]) -> str:
    title = plain_text(work["title"])
    main_image = site_path(str(work["mainImage"]))
    video = str(work.get("mainVideo", "")).strip()
    video_html = ""
    if video:
        video_html = f'''
        <div class="media-container">
            <iframe src="{escape(video, quote=True)}" title="{escape(title, quote=True)} 영상 / Video" allowfullscreen class="media-item main-video" loading="lazy"></iframe>
        </div>'''

    detail_html_parts: list[str] = []
    for image in images:
        detail_html_parts.append(
            f'''        <div class="media-container">
            <img src="{escape(image['src'], quote=True)}" alt="{escape(image['alt'], quote=True)}" class="media-item detail-image" loading="lazy">
        </div>'''
        )
    details = "\n".join(detail_html_parts)

    return f'''                    <div class="work-header">
                        <h1 class="ProjectTitle">{work['title']}</h1>
                        <p class="subtitle">{work.get('subtitle', '')}</p>
                    </div>
                    <div class="work-main">
                        <div class="media-container">
                            <img src="{escape(main_image, quote=True)}" alt="{escape(title, quote=True)}" class="media-item main-image" loading="eager" fetchpriority="high">
                        </div>
                    </div>
                    <div class="work-meta">
                        <p><strong>Year:</strong> {escape(str(work['year']))}</p>
                        <p><strong>Category:</strong> {escape(str(work['분류']))}</p>
                        <p><strong>Key Words:</strong> {escape(str(work.get('keyWords', '')))}</p>
                    </div>
                    <div class="work-abstract">
                        <h3>{work.get('abstract', '')}</h3>
                        <p>{work.get('detail', '')}</p>
                        <br>
                    </div>{video_html}
                    <div class="work-detail">
{details}
                    </div>'''


def structured_data(work: dict, images: list[dict[str, str]], canonical: str) -> str:
    image_urls = [absolute_url(str(work["mainImage"]))]
    image_urls.extend(absolute_url(image["src"]) for image in images)
    payload = {
        "@context": "https://schema.org",
        "@type": "CreativeWork",
        "name": plain_text(work["title"]),
        "url": canonical,
        "description": plain_text(work.get("detail")) or plain_text(work.get("abstract")),
        "dateCreated": str(work["year"]),
        "genre": str(work["분류"]),
        "keywords": plain_text(work.get("keyWords")),
        "image": image_urls,
        "creator": {
            "@type": "Person",
            "name": "Yeoneui Kim 김연의",
            "url": f"{BASE_URL}/about/",
        },
    }
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")


def render_detail(template: str, work: dict, images: list[dict[str, str]]) -> str:
    title = plain_text(work["title"])
    canonical = f"{BASE_URL}/works/{work['slug']}/"
    replacements = {
        "{{PAGE_TITLE}}": escape(f"{title} | Yeoneui Kim 김연의", quote=True),
        "{{META_DESCRIPTION}}": escape(meta_description(work), quote=True),
        "{{CANONICAL_URL}}": escape(canonical, quote=True),
        "{{OG_IMAGE_URL}}": escape(absolute_url(str(work["mainImage"])), quote=True),
        "{{OG_IMAGE_ALT}}": escape(title, quote=True),
        "{{STRUCTURED_DATA}}": structured_data(work, images, canonical),
        "{{ANALYTICS_PATH}}": escape(f"/works/{work['slug']}/", quote=True),
        "{{ANALYTICS_TITLE}}": escape(title, quote=True),
        "{{WORK_CONTENT}}": render_detail_content(work, images),
    }
    output = template
    for key, value in replacements.items():
        output = output.replace(key, value)
    unresolved = re.findall(r"\{\{[A-Z_]+\}\}", output)
    if unresolved:
        raise ValueError(f"Unresolved template values for {work['id']}: {unresolved}")
    return output.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{GENERATED_MARKER}", 1)


def validate_local_assets(works: list[dict], image_map: dict[str, list[dict[str, str]]]) -> None:
    for work in works:
        work_id = str(work["id"])
        paths = {
            "thumbnail": site_path(str(work["thumbnail"])),
            "hover thumbnail": site_path(str(work.get("hoverThumbnail") or derive_hover_thumbnail(str(work["thumbnail"])))),
            "main image": site_path(str(work["mainImage"])),
        }
        for index, image in enumerate(image_map[work_id], start=1):
            paths[f"detail image {index}"] = image["src"]

        for label, value in paths.items():
            parsed = urlparse(value)
            if parsed.scheme or parsed.netloc:
                continue
            local_path = unquote(parsed.path)
            if not local_path.startswith("/assets/"):
                raise ValueError(f"Unexpected {label} path for {work_id}: {value}")
            if not (ROOT / local_path.lstrip("/")).is_file():
                raise ValueError(f"Missing {label} for {work_id}: {value}")


def sitemap(works: list[dict], image_map: dict[str, list[dict[str, str]]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
    ]
    for path in ("/", "/about/", "/works/", "/contact/"):
        lines.extend(("  <url>", f"    <loc>{BASE_URL}{path}</loc>", "  </url>"))
    for work in works:
        canonical = f"{BASE_URL}/works/{work['slug']}/"
        images = [
            {"src": site_path(str(work["thumbnail"])), "alt": plain_text(work["title"])},
            {"src": site_path(str(work["mainImage"])), "alt": plain_text(work["title"])},
            *image_map[str(work["id"])],
        ]
        seen: set[str] = set()
        lines.extend(("  <url>", f"    <loc>{xml_escape(canonical)}</loc>"))
        for image in images:
            image_url = absolute_url(image["src"])
            if image_url in seen:
                continue
            seen.add(image_url)
            lines.extend(
                (
                    "    <image:image>",
                    f"      <image:loc>{xml_escape(image_url)}</image:loc>",
                    f"      <image:title>{xml_escape(plain_text(image.get('alt')))}</image:title>",
                    "    </image:image>",
                )
            )
        lines.extend(("  </url>",))
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    content = content.rstrip() + "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    if check:
        print(f"STALE: {path.relative_to(ROOT)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"WROTE: {path.relative_to(ROOT)}")
    return True


def main() -> int:
    args = arguments()
    try:
        works = load_works()
        template = DETAIL_TEMPLATE_PATH.read_text(encoding="utf-8")
        current_index = WORKS_INDEX_PATH.read_text(encoding="utf-8")
        image_map = {str(work["id"]): detail_images(work) for work in works}
        validate_local_assets(works, image_map)

        stale = False
        for work in works:
            output_path = ROOT / "works" / str(work["slug"]) / "index.html"
            stale |= write_or_check(
                output_path,
                render_detail(template, work, image_map[str(work["id"])]),
                args.check,
            )
        stale |= write_or_check(WORKS_INDEX_PATH, render_index(current_index, works), args.check)
        stale |= write_or_check(SITEMAP_PATH, sitemap(works, image_map), args.check)
        stale |= write_or_check(
            ROBOTS_PATH,
            f"User-agent: *\nAllow: /\n\nSitemap: {BASE_URL}/sitemap.xml\n",
            args.check,
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.check and stale:
        return 1
    print(f"OK: {len(works)} static work pages are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
